config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  get "signup", to: "users#new"
  post "signup", to: "users#create"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users, except: [:new, :create]

  get "home", to: "home#view"
  post 'create', to: 'organisation#create'
  post 'join', to: "employment#join"
  delete 'leave', to: 'employment#destroy'

  resources :users, except: [:new, :create, :destroy, :index] 
  resources :organisation, except: [:index, :show, :new] do
    resources :shifts, only: [:index]
  end

  resources :shifts, except: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :users

  validates :name, presence: true
  validates :hourly_pay_rate, numericality: { greater_than: -1 }
  validates :hourly_pay_rate, format: { with: /\A\d+(?:\.\d{0,2})?\z/,
   message: "must have two decimal points" }
end

app/models/shift.rb
class Shift < ApplicationRecord
  attr_accessor :date, :start, :finish, :break_length
  belongs_to :organisation
  belongs_to :user
  validates :start, presence: true
  validates :finish, presence: :true
  validates_datetime :start
  validates_datetime :finish
  validates :break_length, numericality: {only_integers: true}
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :organisation, optional: true
  has_many :shifts
  
  has_secure_password
  validates :password, length: { minimum: 6, maximum: 20 }, on: :create
  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning, :alert, :notice
  helper_method :current_user, :logged_in?

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to access this page."
      redirect_to root_path
    end
  end

end

app/controllers/employment_controller.rb
class EmploymentController < ApplicationController
  before_action :find_user
  
  def join
    if
      @user.update(employment_params)
      redirect_to home_path
    else
      print employment_params
      redirect_to home_path
    end
  end

  private
  def employment_params
    params.require(:organisation).permit(:organisation_id)
  end

  def find_user
    @user = current_user
  end
end 

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_user

  def view
    @user = current_user

    if @user.organisation
      @organisation = @user.organisation
      render 'home'
    else
      @organisations = Organisation.all
      @organisation = Organisation.new
      render 'non_org_user'
    end
  end
end

app/controllers/organisation_controller.rb
class OrganisationController < ApplicationController
  before_action :set_organisation, except: [:create]

  def create
    @organisation = Organisation.new(organisation_params)
    if @organisation.save
      redirect_to home_path
    else
      @organisations = Organisation.all 
      @user = current_user
      render "home/non_member_show" 
    end
  end

  def edit
  end

  def update
    if @organisation.update(organisation_params)
      redirect_to home_path
    else
      render :edit
    end
  end

  def destroy
    @organisation.destroy
    redirect_to home_path
  end

  private
  def organisation_params
    params.require(:organisation).permit(:name, :hourly_pay_rate)
  end

  def set_organisation
    @organisation = Organisation.find(params[:id])
  end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully."
      redirect_to home_path
    else
      flash[:alert] = "Cannot login. Please try again."
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    flash[:notice] = "You have successfully been logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show_user
    @user = current_user
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to home_path
    else
      flash[:alert] = "Cannot sign up. Please try again."
      redirect_to signup_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/home.html.erb
<h1>Welcome</h1>
<% if logged_in? %>
  <p>Logged in as <%= current_user.name %></p>
  <p><%= button_to 'Log Out', logout_path, method: :delete %></p>
<% end %>

<p>You are currently in:<p><br>
<%= @organisation.name %>
<%= link_to "Edit", edit_organisation_path(@organisation) %>
<%= link_to "View shifts", organisation_shifts_path(@organisation), class: "btn-primary" %>

app/views/home/non_org_user.html.erb
<% if logged_in? %>
<h1>Hey There <%= current_user.name %>!
<strong><%= button_to 'Log Out', logout_path, method: :delete %></strong>
<% end %>

<h2>Join an organisation</h2>
<p>You aren’t a employee of any organisation. Join an existing one or create a new one to join.</p>

<h2>Organisations</h2>
<% @organisations.each do |org| %>
<li>
  <%= org.name %><br>
  <%= button_to "join", join_path, params: { organisation: {organisation_id: org.id} } %>
</li>
<% end %>

<h2>Create Organisation<h3>
<div class="auth-form">
  <%= form_with model: @organisation, url: create_path do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>

    <%= f.label :hourly_pay_rate %><br>
    <%= f.text_field :hourly_pay_rate %><br>

    <%= f.submit "Sign Up", class: "btn-cta" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adnat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/organisation/edit.html.erb
<h2> Edit Details for <%= @organisation.name %> </h2>
<%= form_with model: @organisation do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br><br>
  <%= f.label :hourly_pay_rate %><br>
  <%= f.number_field :hourly_pay_rate %><br>
  <%= f.submit "Save" %>
<% end %>

app/views/users/new.html.erb
<div class="auth-container">
  <% flash.each do |type, msg| %>
    <div class="alert alert-info">
      <%= msg %>
    </div>
  <% end %>
  <div class="auth-form">
    <h1>Sign Up</h1>
    <%= form_with model: @user, url: signup_path do |f| %>
      <%= f.label :name %><br>
      <%= f.text_field :name %><br>

      <%= f.label :email %><br>
      <%= f.email_field :email %><br>

      <%= f.label :password %><br> (6 characters minimum)<br>
      <%= f.password_field :password %><br>

      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %><br>

      <%= f.submit "Sign Up", class: "btn-cta" %>
    <% end %>
  </div>
  <p>Already a member? <strong><%= button_to 'Login', login_path %></strong></p>
</div>